dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- coverage run --branch --source=. ./manage.py test --keepdb
deploy:
  provider: heroku
  app: egc-practicas-pabcargam
  strategy: git
  api_key:
    secure: i3cGcAljwNyNndLqY13Ti6m1YBF+XOnMSTpoL5UCu+n5xMp+l7rLQ1TzeW6jbPXuyCl1Pu64LWslAtflEzKCyy1MziiBQc55YVf4MXSKWqpUM2jmRgHV5VMR1Jjgeo71xxo8P4lriYlrCvyDetF99TfpvEW5NXj8uAlWUeCcFhcypJh4mSLFk5gTNT4Y5i1n6rjGnakTu0hhzkAfLFBle9idMm4Ip8SXOJT3DpxFdr33NO7TL6yOn2vdOJ8W7nS5WYPpeZfuZRHsRQkgQlhW+RYfmj05vydMPQzhyfOjicMplhCF5476L3mJrYKd5bPyo61bF1cMCQM9CcJH9SFWYC4G9YAF8q+RMgg9DMPyYc5N0Ni6BcYfTJQ2rQoC8JNjtIaTQXZv3RtcReMh3L1QxZFZE11qpvw4fvbgmmN3XYwTJ0+PAVE5ExFnHJGCDX8/1OucixOWqgDpzNBmKJIwHZSVrFJ5oNQiP/b4Qq5Vgrma5Zj80SSATZttbGMUXKtG/inK4QH8Fe3TmBkpyWYjbkoyPDHLKH/BAy88r0rNaexpDoOS33pfmB290kzFMaYkCqv0xxMtXlT1nfZ0SRE0CaPtSALfpOloiNmCReBa7qiMpUM5lbtOMY+MO6KDe0i45KypUdH2LRE12MB3aSRo3R59cuR+IPN0nG5swmrErSw=
